mysecret: ENC[AES256_GCM,data:a/0b3czSr0/Uv4RI9jHiKA==,iv:66Be4XBXFsoQXphYBPs+OBc2u4t4n5yYIKZ3ye/wSec=,tag:lMIGt1+L9ObAXeUUYpMvUA==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/gabriel-garrido/locations/global/keyRings/mysopskeyring/cryptoKeys/mysopskey
        created_at: '2019-06-11T11:56:58Z'
        enc: CiQAx1K4ZTbPfHajzZPxLoLghFH+DrW6/GUHIzJcv7o5kP4Ci8QSSQBNlKZZiQHu6/xkkzJU1bRArJ4PkHx5KzJHQCMTqmDowZRBu9dCoVQCfCJiKxOCiOolqMY+7tvh1UecJHS+baWOOMfa4ns7YXA=
    azure_kv: []
    lastmodified: '2019-06-11T11:56:59Z'
    mac: ENC[AES256_GCM,data:js/4BriyKiMsQPptsu9gu+2OURD59hA3C7ZNG3rsIFxw4TgpewZU7CUtb8ekz4z566KaWi0HgKLOJ4shgzqMaSIMrLqufyiv4ssTOmheAz/nmZ6a8fJ5dpY8y6nXlNvxTfjGqaVqvjfT/UUH9UOj/ZWd3n8oRcRLkCBDZEZRjQs=,iv:BycEiwXeQ2nHCqSDXOrnfDct0aCuitweRopmD996wjY=,tag:casLT8lJju/6MuuYXObz0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.0
